### ISSUE TITLE
Birkaç Hata alıyorum

### ISSUE THREAD

**Issue by Phoenix-rat** [falsisdev/site#1]
TypeError: /home/runner/site/src/index.ejs:5
/home/runner/site/src/links.ejs:2

**Comment by Phoenix-rat** [comment]
TypeError: /home/runner/site/src/index.ejs:19
Cannot read property 'pc' of undefined

**Comment by falsisdev** [comment]
bana ait id'leri düzenleyin ve lanyard sunucusuna katılın. sorumluluk size ait.

**Comment by Phoenix-rat** [comment]
Hocam tüm IDleri düzenledim ama nedense hata veriyor.

**Comment by falsisdev** [comment]
Bilemiyorum kendi yazılım bilginizle sorunu çözmeye çalışın.

**Comment by falsisdev** [comment]
Kapatıyorum
